documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "README.md"
          - "CONTRIBUTING.md"

feature:
  - head-branch: ["^feature/"]

fix:
  - head-branch: ["^fix/"]

hotfix:
  - head-branch: ["^hotfix/"]

release:
  - head-branch: ["^release/"]
