words = [
    "actionlint",
    "buildx",
    "classmethod",
    "cli",
    "codebook",
    "codecov",
    "cookiecutter",
    "cooldown",
    "cov",
    "coveragerc",
    "cron",
    "dockerignore",
    "fontawesome",
    "gha",
    "hadolint",
    "ipynb",
    "jaxtyping",
    "junitxml",
    "kfp",
    "kwargs",
    "levelname",
    "nox",
    "opencontainers",
    "posargs",
    "pydantic",
    "pyproject",
    "pytest",
    "reviewdog",
    "rootdir",
    "sqlalchemy",
    "sqruff",
    "sqruffignore",
    "unittests",
    "vscode",
]
